EGI-Federation/fedcloud-vmi-templates

centos/centos-6.json
centos/centos-7.json
ubuntu/docker-ubuntu-18.04.json
ubuntu/provisioners/roles/docker/defaults/main.yaml
ubuntu/provisioners/roles/docker/tasks/main.yaml
ubuntu/ubuntu-16.04.json
ubuntu/ubuntu-18.04.json

Getting new versions for all VMs expiring now

Jan upgrade

---

ubuntu/appdb/ubuntu-20.04.yaml
ubuntu/httpdir/user-data
ubuntu/provisioners/base.yaml
ubuntu/provisioners/init.yaml
ubuntu/provisioners/roles/cleanup/tasks/main.yaml
ubuntu/provisioners/roles/cloud-init/tasks/cloud-init-focal.yaml
ubuntu/ubuntu-20.04.json

Ubuntu 20.04

---

centos/appdb/centos-8.yaml
centos/centos-8.json
centos/httpdir/centos-8.cfg

- Update centos 8
- Add AppDB metadata

Centos8 regular update

---

ubuntu/appdb/appliance.yaml
ubuntu/fedcloud-appliance.json
ubuntu/provisioners/appliance.yaml
ubuntu/provisioners/roles/appliance/defaults/main.yaml

- Update appliance provisioning
- Update version
- Update AppDB metadata

appliance update

---

ubuntu/appdb/small-ubuntu-16.04.yaml
ubuntu/small-ubuntu-16.04.json

- Regular update
- AppDB info update

monitoring update 2021 09

---

centos/appdb/centos-7.yaml
centos/centos-7.json

Regular update as image expires now﻿

Update CentOS 7

---

ubuntu/appdb/ubuntu-22.04.yaml
ubuntu/provisioners/roles/cloud-init/tasks/cloud-init-jammy.yaml
ubuntu/ubuntu-22.04.json

Ubuntu 22.04

---

ubuntu/appdb/small-ubuntu-18.04.yaml
ubuntu/small-ubuntu-18.04.json

Just an update before the image expires

Update of monitoring image

---

centos/appdb/centos-8.yaml
centos/centos-8.json

- CentOS 8 regular update
- AppDB update

centos8 update 2022 10

---

centos/appdb/centos-8.yaml
centos/centos-8.json
centos/httpdir/centos-8.cfg.tpl
centos/provisioners/clean.yaml

Update centos 8 image, move it to kvm building
---

Centos 8 update

---

ubuntu/appdb/ubuntu-20.04.yaml
ubuntu/ubuntu-20.04.json

As other images move to kvm
Yet another update, should have put them all together
---

Ubuntu 20.04 Update

---

centos/appdb/centos-7.yaml
centos/centos-7.json
ubuntu/appdb/datahub-jupyter-ubuntu-20.04.yaml
ubuntu/appdb/ubuntu-18.04.yaml
ubuntu/datahub-jupyter-ubuntu-20.04.json
ubuntu/ubuntu-18.04.json

Update centos 7, Ubuntu 8 and DataHub Jupyter

---

centos/appdb/centos-8.yaml
centos/centos-8.json
ubuntu/appdb/ubuntu-20.04.yaml
ubuntu/appdb/ubuntu-22.04.yaml
ubuntu/ubuntu-20.04.json
ubuntu/ubuntu-22.04.json

Update images that are already expired

---

ubuntu/appdb/monitoring.yaml
ubuntu/small-ubuntu-20.04.json

Regular update before image expires.
Had to increase the disk size to avoid build errors
---

Update of small ubuntu

---

centos/appdb/centos-7.yaml
centos/centos-7.json
ubuntu/appdb/datahub-jupyter-ubuntu-20.04.yaml
ubuntu/datahub-jupyter-ubuntu-20.04.json

Updates 2 images expiring in 15 days.
Not updating ubuntu 18.08 as it has reached EOL. Will be removed soon (keeping it while it is still has not expired in AppDB)

Jan 2024 updates

---

ubuntu/appdb/ubuntu-22.04.yaml

Current EGI image is failing to reboot when started with IM, moving to the official ubuntu image while we figure out the exact issue.
---

Use ubuntu from official images

---

ubuntu/appdb/ubuntu-22.04.yaml

This reverts commit ac58f2a5d26b3e223baeb7d9ee179f5fd2b563c6.
---
**Related issue :** https://github.com/EGI-Federation/fedcloud-vmi-templates/issues/62

Revert "Use ubuntu from official images (#63)"

---

ubuntu/appdb/docker.yaml
ubuntu/docker-ubuntu-22.04.json
ubuntu/provisioners/roles/cleanup/tasks/main.yaml
ubuntu/provisioners/roles/cloud-init/tasks/cloud-init-jammy.yaml
ubuntu/provisioners/roles/docker/tasks/main.yaml

Regular update of docker VM image
Brings new versions of the docker and kubernetes components
---

Docker update

---

ubuntu/appdb/ubuntu-20.04.yaml
ubuntu/ubuntu-20.04.json

Update to the image as it's expiring in 4 days
---

Regular Ubuntu 20.04 update

---

ubuntu/appdb/ubuntu-24.04.yaml
ubuntu/provisioners/roles/cloud-init/tasks/cloud-init-noble.yaml
ubuntu/ubuntu-24.04.json

Ubuntu 24.04 ready to be used at EGI
---

New Ubuntu 24.04

---

ubuntu/appdb/monitoring.yaml
ubuntu/small-ubuntu-20.04.json

Update small ubuntu, just rebuild

---

.github/dependabot.yml
.github/workflows/shasum.yml
README.md
builder/cloud-init.yaml
centos/provisioners/config.yaml
centos/provisioners/init.yaml
ubuntu/provisioners/appliance.yaml
ubuntu/provisioners/docker.yaml
ubuntu/provisioners/init.yaml
ubuntu/provisioners/jupyterhub.yaml
ubuntu/provisioners/roles/appliance/defaults/main.yaml
ubuntu/provisioners/roles/appliance/tasks/main.yaml
ubuntu/provisioners/roles/cleanup/tasks/main.yaml
ubuntu/provisioners/roles/cloud-init/tasks/cloud-init-focal.yaml
ubuntu/provisioners/roles/docker/tasks/main.yaml

Being nicer with the linter
---

Linting fixes

---

builder/build-image.sh
ubuntu/ubuntu-22.04.json

Compress resulting image to make things lighter
---

Compress resulting qcow2 image

---

.github/workflows/build.yml
builder/build-image.sh
ubuntu/ubuntu-22.04.json

Fix the compression added in #79 
---
**Related issue :** #79

compress again

---

ubuntu/appdb/ubuntu-22.04.yaml

Updates Ubuntu 22.04 to latest version using image built in #81
---
**Related issue :** #81

Update image from build

---

ubuntu/datahub-jupyter-ubuntu-22.04.pkr.hcl

Regular update of datahub jupyter VM

---

ubuntu/appdb/datahub-jupyter-ubuntu-22.04.yaml

... this could be probably automated as well ;)
---

Update appdb metadata

---

ubuntu/appdb/docker.yaml
ubuntu/docker-ubuntu-22.04.pkr.hcl
ubuntu/provisioners/roles/docker/tasks/main.yaml

Update docker image

---

builder/build-image.sh
ubuntu/ubuntu-20.04.pkr.hcl

Update Ubuntu 20.04

---

ubuntu/appdb/ubuntu-20.04.yaml

As built in #98
---
**Related issue :** #98

Update AppDB information for Ubuntu 20.04

---

.github/workflows/shasum.yml
ubuntu/appdb/ubuntu-22.04.yaml
ubuntu/provisioners/init.yaml
ubuntu/ubuntu-22.04.pkr.hcl

- **Add skel files to ubuntu user**
- **Upgrade ubuntu 22**
---

Skel files

---

builder/build-image.sh
builder/cloud-init.yaml
builder/upload.sh

Add annotations to the push of the images.
---

Include annotations

---

ubuntu/ubuntu-24.04.pkr.hcl

Regular update of Ubuntu 24.04 and testing of the new push system
---

New version of ubuntu 24.04

---

builder/build-image.sh
builder/upload.sh
ubuntu/ubuntu-20.04.pkr.hcl

Improve how the annotations are included with the images
---

Annotations improvement

---

ubuntu/datahub-jupyter-ubuntu-22.04.pkr.hcl
ubuntu/provisioners/datahub-jupyter.yaml

Move to pip based installation and update image
---

Avoid conda in jupyter image

---

.github/workflows/build.yml

Using proposed solution at https://github.com/dorny/paths-filter/issues/66
---

Try to avoid an error when no build is done

---

builder/build-image.sh
builder/upload.sh

Solve issues in:https://github.com/EGI-Federation/fedcloud-vmi-templates/actions/runs/13453264262/job/37591657369
---

Hide qcow2 files after build

---

builder/build-image.sh
builder/upload.sh

bugfix jq command to extract VM_NAME

---

builder/build-image.sh
builder/upload.sh

Fix the jq cmd

---

.github/workflows/trigger-build.yml

See docs https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow
---

Use the proper event

---

.github/workflows/trigger-build.yml

bugfix find cmd in all_images in workflow to trigger build

---

.github/workflows/build-changes.yml

Avoid tj-actions/changed-files as it is a potential source of security issues.
---
**Related issue :** #129

Remove tj-actions/changed-files

---

.github/workflows/build.yml
ubuntu/datahub-jupyter-ubuntu-22.04.pkr.hcl
ubuntu/docker-ubuntu-22.04.pkr.hcl
ubuntu/provisioners/datahub-jupyter.yaml

Updates images from AppDB while registry is still not fully operational for syncing
---
**Related issue :** https://github.com/EGI-Federation/fedcloud-dashboard/issues/68

Appdb images update

---

ubuntu/appdb/datahub-jupyter-ubuntu-22.04.yaml
ubuntu/appdb/docker.yaml

Update AppDB metadata
---
**Related issue :** #127

Update AppDB images metadata

---

ubuntu/appdb/ubuntu-20.04.yaml
ubuntu/ubuntu-20.04.pkr.hcl

Regular update of the image
---

Ubuntu 20.04 update (appdb)

---

ubuntu/appdb/ubuntu-24.04.yaml
ubuntu/ubuntu-24.04.pkr.hcl

Update Ubuntu 24 image

---

builder/upload.sh

Play nicer with potential consumers
---

Add mime type to the image layer

---

.github/workflows/build.yml
builder/build-image.sh
builder/upload.sh
builder/vm.tf
ubuntu/provisioners/base.yaml
ubuntu/provisioners/cleanup.sh
ubuntu/provisioners/roles/trivy/tasks/main.yaml
ubuntu/ubuntu-24.04.pkr.hcl

Creates a SBOM for the image using trivy and uploads it to the registry
---
**Related issue :** #139

Produce SBOM for image

---

builder/upload.sh

fix: add missing space for SBOM upload to work

---

builder/upload.sh

Fix: typo on API call
